apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: 
  name: cucp-example
  namespace: example
spec:
  provider: cucp.openairinterface.org
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: cucp-nf-config
