apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: 
  name: du-example
  namespace: example
spec:
  provider: du.openairinterface.org
  parametersRefs:
    - apiVersion: workload.nephio.org/v1alpha1
      kind: NFConfig
      name: du-nf-config