apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-configsync
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: configsync
    repo: catalog-nephio-core
    workspaceName: v6.0.0
  downstream:
    package: example-configsync
    repo: mgmt-staging
  injectors:
  - kind: WorkloadCluster
    name: example
  pipeline:
    mutators:
    - image: ghcr.io/kptdev/krm-functions-catalog/set-annotations:v0.1.4
      configMap:
        nephio.org/cluster-name: example
