---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nrf-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
  namespace: free5gc-cp
data:
  nrfcfg.yaml: |
    info:
      version: 1.0.2
      description: NRF initial local configuration

    configuration:
      MongoDBName: free5gc
      MongoDBUrl: mongodb://mongodb:27017

      serviceNameList:
        - nnrf-nfm
        - nnrf-disc

      sbi:
        scheme: http
        registerIPv4: nrf-nnrf  # IP used to serve NFs or register to another NRF
        bindingIPv4: 0.0.0.0    # IP used to bind the service
        port: 8000
        tls:
          key: cert/nrf.key
          pem: cert/nrf.pem
        rootcert:
          pem: cert/nrf.pem
          key: cert/nrf.key
        oauth: true
      DefaultPlmnId:
        mcc: 208
        mnc: 93

      metrics:
        enable: false
        scheme: http
        bindingIPv4: 0.0.0.0
        port: 9091
        tls:
          pem: cert/nrf.pem
          key: cert/nrf.key
        namespace: free5gc-cp
    logger:
      enable: true
      level: info
      reportCaller: false
