---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-configmap
  labels:
    app.kubernetes.io/version: "v3.1.1"
    app: free5gc
data:
  ausfcfg.yaml: |
    info:
      version: 1.0.3
      description: AUSF initial local configuration

    configuration:
      serviceNameList:
        - nausf-auth
      
      sbi:
        scheme: http
        registerIPv4: ausf-nausf  # IP used to register to NRF
        bindingIPv4: 0.0.0.0      # IP used to bind the service
        port: 80
        tls:
          key: cert/ausf.key
          pem: cert/ausf.pem
      
      nrfUri: http://nrf-nnrf:8000
      nrfCertPem: cert/nrf.pem  
      plmnSupportList:
        - mcc: 208
          mnc: 93
        - mcc: 123
          mnc: 45
      groupId: ausfGroup001
      eapAkaSupiImsiPrefix: false

      metrics:
        enable: false
        scheme: http
        bindingIPv4: 0.0.0.0
        port: 9091
        tls:
          pem: cert/ausf.pem
          key: cert/ausf.key
        namespace: free5gc-cp

    logger:
      enable: true
      level: info
      reportCaller: false
